# Generated by Django 5.0.3 on 2024-03-21 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_customuser_name_alter_customuser_verification_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Projet', max_length=64)),
                ('description', models.CharField(default='Votre description', max_length=256)),
                ('version', models.CharField(default='0.0.1', max_length=8)),
                ('repository_url', models.CharField(default='git/default/url', max_length=2048)),
                ('user_id', models.IntegerField(default=0)),
            ],
        ),
    ]
